### ISSUE TITLE
SpeedSeq SV doesn't  run on re-aligned BAM files

### ISSUE THREAD

**Issue by snamburi3** [hall-lab/speedseq#84]
Hi All,

I think *speedeq realign* does not retain the RG information from the original BAM file. *speedseq sv* on realigned BAM files fails.  Below is the error message. Could you please help me with this? 
```
**../bin/speedseq sv     -o example     -B example.realign.bam     -S example.splitters.bam     -D example.discordants.bam     -R data/human_g1k_v37_20_42220611-42542245.fasta
Sourcing executables from ../bin/speedseq.config ...**

Checking for required python modules (/usr/bin/python2.7)...

        create temporary directory

Running LUMPY express
Sourcing executables from ../bin/speedseq.config ...

Checking for required python modules (/usr/bin/python2.7)...

    create temporary directory
Calculating insert distributions... 
Library read groups: NA12878
Library read length: 101
Traceback (most recent call last):
  File "/opt/speedseq//bin/bamfilterrg.py", line 127, in <module>
    sys.exit(main())
  File "/opt/speedseq//bin/bamfilterrg.py", line 123, in main
    bamfilterrg(args.input, args.readgroup, args.n, args.S, args.b, args.u)
  File "/opt/speedseq//bin/bamfilterrg.py", line 49, in bamfilterrg
    if rg_list and al.opt('RG') not in rg_list:
  File "pysam/calignedsegment.pyx", line 2284, in pysam.calignedsegment.AlignedSegment.opt (pysam/calignedsegment.c:25658)
  File "pysam/calignedsegment.pyx", line 1956, in pysam.calignedsegment.AlignedSegment.get_tag (pysam/calignedsegment.c:20683)
KeyError: "tag 'RG' not present"
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/opt/speedseq//bin/pairend_distro.py", line 106, in <module>
    (removed, upper_cutoff))
TypeError: %d format: a number is required, not numpy.float64

```

**Comment by cc2qe** [comment]
can you please paste the BAM header from the original BAM file as well as the realigned BAM file? I just want to see how the RG information changed

If you have the command you used to run speedseq realign, can you also share that?

**Comment by snamburi3** [comment]
Thanks you for your help! I used the [example script](https://github.com/hall-lab/speedseq/blob/master/example/run_speedseq.sh) and data provided with SpeedSeq. I provided the realigned bam file from step4 to *speedseq sv* in the step3. 

speedseq realign command:
```
./bin/speedseq realign -o example.realign  -M 3  data/human_g1k_v37_20_42220611-42542245.fasta example.bam
```

* header info:
```
root@3454814ddfeb:/opt/speedseq/example# samtools view -h example.bam | head
@HD	VN:1.3	SO:coordinate
@SQ	SN:20_slice	LN:321635
@RG	ID:NA12878	LB:lib1	SM:NA12878
@PG	ID:bwa	PN:bwa	CL:/opt/speedseq//bin/bwa mem -t 1 -p -R @RG\tID:NA12878\tSM:NA12878\tLB:lib1 data/human_g1k_v37_20_42220611-42542245.fasta data/NA12878.20slice.30X.fastq.gz	VN:0.7.10-r789
@PG	ID:SAMBLASTER	CL:samblaster -i stdin -o stdout --excludeDups --addMateTags -d example.QpVSclRWyNRJ/disc_pipe -s example.QpVSclRWyNRJ/spl_pipe --maxSplitCount 2 --maxUnmappedBases 50 --minIndelSize 50 --minNonOverlap 20	VN:0.1.22
ERR091571.143176384	99	20_slice	1	60	5S96M	=	5	105	TATAGGGATTTATTATATAGGCGAGGTGGTACTGTATTTCAAATCAGCATTGAAGAGATGAATTGGGGTCAGGCAGCTTTTTTAGCAATTTAGAAAATAAT	CCCFFFFDHHHGHJJJJJJIIFHGII:?G:DHIJIJIIJIIIIJJJJIHIIIGJIIICHIIIJGHIJE:BBFEFDABEDDDDD?CCCDDDDDDDCDDCDCC	NM:i:0	MD:Z:96	AS:i:96	XS:i:0	RG:Z:NA12878	MC:Z:101M	MQ:i:60
ERR091571.76317268	163	20_slice	1	60	61S40M	=	81	181	GCAGGAGCTTACAGGTAGATAAAATATATTAGAACTCAGAATAAGAGCGATTTATATATAGGGATTTATTATATAGGCGAGGTGGTACTGTATTTCAAATG	?@@ADBDFHHHHHIG<CFDHHIJJIGG>CHD>F?EDHIGIHIII9DDGIIHHD?D?H<CGGBGGCHI>FHAGEG@@D;B6?=,5?9;@A@;(;;@;;AAA#	NM:i:1	MD:Z:39C0	AS:i:39	XS:i:0	RG:Z:NA12878	MC:Z:101M	MQ:i:60
ERR091572.170612544	99	20_slice	1	60	53S48M	=	86	186	TTACAGGTAGATAAAATATATTAGAACTCAGAATAAGAGCGATTTATATATAGGGATTTATTATATAGGCGAGGTGGTACTGTATTTCAAATCAGCATTGA	BCCFFFFDFHHFFIIIIIIJGJIGJIJJJJIJJJJJIGIFIIJJJJJJIHIIJJGIJIJIIJJJJIJIGIGEHB,6@9ACEECEEEDDEDDACCDCDDDDC	NM:i:0	MD:Z:48	AS:i:48	XS:i:0	RG:Z:NA12878	MC:Z:101M	MQ:i:60
ERR091572.53897116	163	20_slice	1	60	74S27M	=	111	211	AGTTTGGGACTCAGCAGGAGCTTACAGGTAGATAAAATATATTAGAACTCAGAATAAGAGCGATTTATATATAGGGATTTATTATATAGGCGAGGTGGTAC	CCBFFFFFGHHHHIJJJIHIJJJJJIJICFIJJFIHJJJJJJJJJJJIJJIJJJJJJJIJJJIIJJJJJJJHHHHHHFFFFFFFEEFEEEDDDDD8?B<CA	NM:i:0	MD:Z:27	AS:i:27	XS:i:0	RG:Z:NA12878	MC:Z:101M	MQ:i:60
ERR091572.6783021	163	20_slice	1	60	54S47M	=	111	211	CTTACAGGTAGATAAAATATATTAGAACTCAGAATAAGAGCGATTTATATATAGGGATTTATTATATAGGCGAGGTGGTACTGTATTTCAAATCAGCATTG	BCCFFFFFCFHHHJJJJJJJJJJJJJJJJJJJJJJJJJIJJJIJJJJJJJIIJJJJJJIJJJJJJJJJIJJIJHF=BE>CEEEFFEEEEEDDDDDDDDDDC	NM:i:0	MD:Z:47	AS:i:47	XS:i:0	RG:Z:NA12878	MC:Z:101M	MQ:i:60



root@3454814ddfeb:/opt/speedseq/example# samtools view -h example.realign.bam | head
@HD	VN:1.3	SO:coordinate
@SQ	SN:20_slice	LN:321635
@RG	ID:NA12878	LB:lib1	SM:NA12878
@PG	ID:bwa	PN:bwa	CL:/opt/speedseq//bin/bwa mem -t 1 -p data/human_g1k_v37_20_42220611-42542245.fasta example.realign.pJ012ideyfDg/fq_pipe	VN:0.7.10-r789
@PG	ID:SAMBLASTER	CL:samblaster -i stdin -o stdout --excludeDups --addMateTags -d example.realign.pJ012ideyfDg/disc_pipe -s example.realign.pJ012ideyfDg/spl_pipe --maxSplitCount 2 --maxUnmappedBases 50 --minIndelSize 50 --minNonOverlap 20	VN:0.1.22
ERR091571.143176384	99	20_slice	1	60	5S96M	=	5	105	TATAGGGATTTATTATATAGGCGAGGTGGTACTGTATTTCAAATCAGCATTGAAGAGATGAATTGGGGTCAGGCAGCTTTTTTAGCAATTTAGAAAATAAT	CCCFFFFDHHHGHJJJJJJIIFHGII:?G:DHIJIJIIJIIIIJJJJIHIIIGJIIICHIIIJGHIJE:BBFEFDABEDDDDD?CCCDDDDDDDCDDCDCC	NM:i:0	MD:Z:96	AS:i:96	XS:i:0	MC:Z:101M	MQ:i:60
ERR091571.76317268	163	20_slice	1	60	61S40M	=	81	181	GCAGGAGCTTACAGGTAGATAAAATATATTAGAACTCAGAATAAGAGCGATTTATATATAGGGATTTATTATATAGGCGAGGTGGTACTGTATTTCAAATG	?@@ADBDFHHHHHIG<CFDHHIJJIGG>CHD>F?EDHIGIHIII9DDGIIHHD?D?H<CGGBGGCHI>FHAGEG@@D;B6?=,5?9;@A@;(;;@;;AAA#	NM:i:1	MD:Z:39C0	AS:i:39	XS:i:0	MC:Z:101M	MQ:i:60
ERR091572.170612544	99	20_slice	1	60	53S48M	=	86	186	TTACAGGTAGATAAAATATATTAGAACTCAGAATAAGAGCGATTTATATATAGGGATTTATTATATAGGCGAGGTGGTACTGTATTTCAAATCAGCATTGA	BCCFFFFDFHHFFIIIIIIJGJIGJIJJJJIJJJJJIGIFIIJJJJJJIHIIJJGIJIJIIJJJJIJIGIGEHB,6@9ACEECEEEDDEDDACCDCDDDDC	NM:i:0	MD:Z:48	AS:i:48	XS:i:0	MC:Z:101M	MQ:i:60
ERR091572.53897116	163	20_slice	1	60	74S27M	=	111	211	AGTTTGGGACTCAGCAGGAGCTTACAGGTAGATAAAATATATTAGAACTCAGAATAAGAGCGATTTATATATAGGGATTTATTATATAGGCGAGGTGGTAC	CCBFFFFFGHHHHIJJJIHIJJJJJIJICFIJJFIHJJJJJJJJJJJIJJIJJJJJJJIJJJIIJJJJJJJHHHHHHFFFFFFFEEFEEEDDDDD8?B<CA	NM:i:0	MD:Z:27	AS:i:27	XS:i:0	MC:Z:101M	MQ:i:60
ERR091572.6783021	163	20_slice	1	60	54S47M	=	111	211	CTTACAGGTAGATAAAATATATTAGAACTCAGAATAAGAGCGATTTATATATAGGGATTTATTATATAGGCGAGGTGGTACTGTATTTCAAATCAGCATTG	BCCFFFFFCFHHHJJJJJJJJJJJJJJJJJJJJJJJJJIJJJIJJJJJJJIIJJJJJJIJJJJJJJJJIJJIJHF=BE>CEEEFFEEEEEDDDDDDDDDDC	NM:i:0	MD:Z:47	AS:i:47	XS:i:0	MC:Z:101M	MQ:i:60

```

**Comment by cc2qe** [comment]
Is there any chance you were using a version of SpeedSeq prior to this commit?
https://github.com/hall-lab/speedseq/commit/815abec5b5f91f1a7f00042f630cda0161781c3b

This issue seems to be related to a bug that I patched last week (related to this issue: https://github.com/hall-lab/speedseq/issues/82)

Let me know if it persists after you update speedseq

**Comment by snamburi3** [comment]
Yes, you are right! I was using the SpeedSeq version from two weeks ago. The commit ```815abec``` solves the issue. My bad, I did not see the commit before opening this issue. Thank you, Colby.
